## NOTE ##
# Plot the barchart of cases generated by RF
# Quite the same with Extract_Cases_Country.R
## ---- ##

library(ggplot2)
library(tidyr)

cat('===== START [Extract_Cases_Country_RF.R] =====\n')

# Get directory of the script (this part only work if source the code, wont work if run directly in the console)
# This can be set manually !!!
script.dir <- dirname(sys.frame(1)$ofile)
script.dir <- paste0(script.dir, '/')
setwd(script.dir)

# Create folder to store the result (will show warnings if the folder already exists --> but just warning, no problem)
dir.create(file.path('Generate'), showWarnings = TRUE)

LinkData <- '../Generate_Cases/' # Data folder is from the Generate_Cases part

Extract_Values_Country <- function(DF_Vals, DF_Coords, Index){
    # Extract values of entire map based on their countries
    # DF_Vals: Dataframe containing values in entire map
    # DF_Coords: Dataframe containing pixel's index indicating which country it belongs to
    # Index: Name of index in DF_Coords
    # Index + DF_Coords has to match
    # Coords in DF_Vals + DF_Coords have to match
    
    result <- vector('list', length(Index))
    names(result) <- Index
    # Check Coord match
    dx <- abs(DF_Vals$x - DF_Coords$x)
    dy <- abs(DF_Vals$y - DF_Coords$y)
    if (dx == 0 && dy == 0){
        for (idx.country in 1 : length(Index)){
            idx_point <- which(DF_Coords[[3]] == idx.country)
            if (length(idx_point) > 0){
                vals <- DF_Vals[[3]][idx_point]
                result[[idx.country]] <- vals
            }
        }
    }else{
        cat('COORDINATES DO NOT MATCH --> STOP!!!\n')
    }
    return(result)
}

# Read data from generated cases dataframe (from Generate Cases part)
Link_Generate_Cases_DF <- paste0(LinkData, 'Generate/Cases/')
ListFiles <- list.files(Link_Generate_Cases_DF)

##### Read Map data #####
Country_Index <- readRDS(paste0(LinkData, "Generate/Country_Index.Rds")) # index of countries
Coord_Regions_Final <- readRDS(paste0(LinkData, "Generate/Coord_Regions_Final.Rds")) # country index of each pixel
Cases.map <- readRDS(paste0(LinkData, "Generate/Cases/", ListFiles[length(ListFiles)])) # Take total cases (index 101)

Cases.map <- Extract_Values_Country(Cases.map, Coord_Regions_Final, Country_Index)
# Fix Low.NPL and High.NPL
Cases.map$NPL <- c(Cases.map$Low.NPL, Cases.map$High.NPL)
Cases.map$MAC <- NULL
Cases.map$Low.NPL <- NULL
Cases.map$High.NPL <- NULL
# Add HKG in CHN
Cases.map$CHN <- c(Cases.map$CHN, Cases.map$HKG)
Cases.map$HKG <- NULL

# Sum cases in all pixels
for (idx in 1 : length(Cases.map)){
    Cases.map[[idx]] <- sum(Cases.map[[idx]])
}

# CREATE DATAFRAME TO PLOT
Countries <- names(Cases.map)
df <- data.frame(country = Countries, cases = 0)
df$country <- as.character(df$country)
for (idx in 1 : nrow(df)){
    country <- df$country[idx]
    df$cases[idx] <- Cases.map[[which(names(Cases.map) == country)]]
}
df$cases <- round(df$cases)

df$country <- factor(df$country, levels = unique(df$country[order(df$cases)]), ordered = TRUE) # order based on cases values

##### SUBPLOT #####
part1 <- levels(df$country)[1 : 6]
part2 <- levels(df$country)[7 : 16]
part3 <- levels(df$country)[17 : 23]
part4 <- levels(df$country)[24 : 25]

df$Part <- 0
df$Part[which(df$country %in% part1)] <- '[1] Below 400 Cases'
df$Part[which(df$country %in% part2)] <- '[2] 400 - 2000 Cases'
df$Part[which(df$country %in% part3)] <- '[3] 2000 - 20000 Cases'
df$Part[which(df$country %in% part4)] <- '[4] Above 20000 Cases'

p <- ggplot(df, aes(x = country, y = cases, label = country)) + 
    geom_bar(stat = 'identity', position = position_dodge(), alpha = 0.75, fill = '#17ad3a') + 
    geom_text(size = 3.5, position = position_stack(vjust = 0.5))
p <- p + theme(axis.text.x = element_text(angle = 90))
p <- p + facet_wrap(~Part, scale = 'free_y', ncol = 1)
p <- p + labs(x = 'Countries', y = 'Cases')
p <- p + theme(
    strip.text.x = element_text(size = 12),
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12)
)

p

cat('===== FINISH [Extract_Cases_Country_RF.R] =====\n')

# SAVE FILE
ggsave(filename = 'Generate/Cases_RF.png', width = 108*2.5, height = 72*2.5, units = 'mm', plot = p)
