##########################
### Extract from original file: JE_FOI_infe_quantities_gen.R (from Quan code)
##########################
### Burdens estimation of WHO-IG generated by Quan method (Rcpp)
##########################
library(Rcpp)
library(dplyr)

cat('===== START [Quan_Cases.R] =====\n')

# Get directory of the script (this part only work if source the code, wont work if run directly in the console)
# This can be set manually !!!
script.dir <- dirname(sys.frame(1)$ofile)
script.dir <- paste0(script.dir, '/')
setwd(script.dir)

# Create folder to store the result (will show warnings if the folder already exists --> but just warning, no problem)
dir.create(file.path('Generate'), showWarnings = TRUE)

# Read modelled FOI + symptomatic + mortality rate used by Quan
# ende_24_regions <- readRDS('~/DuyNguyen/JE_model_Quan/results/areas_lambda/ende_24_regions_lambda_extr_or.rds')
# symp_rate_dist <- readRDS("~/DuyNguyen/JE_model_Quan/data/uncertainty_quantities/symp_rate_dist.rds")
# mort_rate_dist <- readRDS("~/DuyNguyen/JE_model_Quan/data/uncertainty_quantities/mort_rate_dist.rds")
LinkData <- '../Generate_Cases/Data/'
ende_24_regions <- readRDS(paste0(LinkData, 'ende_24_regions_lambda_extr_or.rds'))
symp_rate_dist <- readRDS(paste0(LinkData, "symp_rate_dist.rds"))
mort_rate_dist <- readRDS(paste0(LinkData, "mort_rate_dist.rds"))

#Population data:
all_region_pop <- readRDS(paste0(LinkData, "Naive_pop_24ende_1950_2015.rds"))
all_region_pop <- all_region_pop[, c(1,67)] # take year 2015

# all_region_pop <- readRDS('~/DuyNguyen/RProjects/OUCRU JE/Compare Values/Naive_pop_24ende_1950_2015_Adjust.rds')

#Cases generation function:
cppFunction('NumericMatrix cpp_cases_gen(NumericVector FOI_value, NumericVector symp_rate, NumericVector risk_pop_demo) {
            NumericMatrix cases_gen_dist(FOI_value.size(), risk_pop_demo.size());
            for(int sample = 0; sample < FOI_value.size(); ++sample){
            int age_v = 0;
            for(int i = 0; i < risk_pop_demo.size(); ++i){
            cases_gen_dist(sample,i) = (1 - pow(2.718281828459, -FOI_value[sample]))*symp_rate[sample]*pow(2.718281828459, -FOI_value[sample]*age_v)*risk_pop_demo[i];
            if(age_v < 99){
            ++age_v ;
            } else {
            age_v = 0;
            }
            }
            }
            return(cases_gen_dist);
            }')

#Cases generation:
cases_gen_func <- function(pop_data, FOI_data ,sel_region){
    cases_gen_region = list()
    for(region_i in sel_region){
        region_name = FOI_data$region[region_i] %>% as.character()
        print(region_name)
        FOI_value_region = FOI_data$lambda_extr[[region_i]]
        pop_ende = filter(pop_data, region == region_name) %>% select(starts_with("X")) %>% unlist 
        cases_gen_region[[region_i]] = cpp_cases_gen(FOI_value_region, symp_rate_dist, pop_ende) %>% round(2)
    }
    names(cases_gen_region) = FOI_data$region
    cases_gen_region[sapply(cases_gen_region, is.null)] <- NULL
    return(cases_gen_region)
}

select_region = c(1:6, 11:15, 19:24, 28:30, 32:40, 48) # Selected regions from Quan
no_vac_cases_gen = cases_gen_func(pop_data = all_region_pop,FOI_data = ende_24_regions, sel_region = select_region)

no_vac_cases_gen_age_sum <- no_vac_cases_gen
for (idx in 1 : length(no_vac_cases_gen_age_sum)){
    no_vac_cases_gen_age_sum[[idx]] <- rowSums(no_vac_cases_gen[[idx]])
}

cat('===== FINISH [Quan_Cases.R] =====\n')

# Save generated file
saveRDS(no_vac_cases_gen_age_sum, 'Generate/no_vac_cases_gen_age_sum_or_Regenerated_from_Quan.Rds')
